
# docker build --rm --no-cache --force-rm -f Dockerfile-2b -t microdnf-test2b .
# docker run --rm -it microdnf-test2b
# docker rmi microdnf-test2b

FROM registry.access.redhat.com/rhel7-atomic
MAINTAINER Martin Jenner "mjenner@redhat.com"

# We will run update twice to test the case where there are no rpms to update
RUN microdnf update --enablerepo=rhel-7-server-rpms && microdnf clean all
# Second run should have no rpms to update but not cause build failure
RUN microdnf update --enablerepo=rhel-7-server-rpms && microdnf clean all
